spring:
  sql:
    init:
      mode: always # 애플리케이션 실행 시 SQL 스크립트 자동 실행 방지 -> 최초 실행 후 never로 변경
      continue-on-error: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/ktbworld
    username: krampoline
    password: krampolinepw

  jpa:
    hibernate:
      ddl-auto: create # Hibernate가 데이터베이스 스키마를 변경하지 않도록 설정
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
